[package]
name = "builder-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[[test]]
name = "tests"


[dev-dependencies]
trybuild = {version = "1.0.57", features = ["diff"] }


[dependencies]
syn = {version = "1.0.9", features = ["extra-traits"] }
quote = {version = "1.0.17"}
proc-macro2 = "1.0.36"
